// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSoft.Financial.Data;

#nullable disable

namespace Accounting.Migrations.DbContextFinancialMigrations
{
    [DbContext(typeof(DbContextFinancial))]
    [Migration("20250407055552_InitialFinancial")]
    partial class InitialFinancial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eSoft.Financial.Model.FcAccount", b =>
                {
                    b.Property<int>("FcAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcAccountId"), 1L, 1);

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FcTahun")
                        .HasColumnType("int");

                    b.Property<string>("GlAcct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GlFisc1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc10")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc11")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc12")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc3")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc4")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc5")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc7")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc8")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlFisc9")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("GlKurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlNama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GlPost")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GlPreFisc1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc10")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc11")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc12")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc3")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc4")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc5")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc6")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc7")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc8")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlPreFisc9")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlSaldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GlSldAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("GlStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GlTipe")
                        .HasColumnType("int");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipeGl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FcAccountId");

                    b.ToTable("FcAccounts");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcCom", b =>
                {
                    b.Property<int>("FcComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcComId"), 1L, 1);

                    b.Property<string>("FcAlamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FcFiscalYear")
                        .HasColumnType("int");

                    b.Property<string>("FcNamaPerusahaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlAcct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlAcct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlAcct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlAcct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlAcct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlAcct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept6")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FcComId");

                    b.ToTable("FcComs");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcGlTransD", b =>
                {
                    b.Property<int>("FcGlTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcGlTransDId"), 1L, 1);

                    b.Property<decimal>("Debet")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FcGlTransHId")
                        .HasColumnType("int");

                    b.Property<string>("GlAcct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumKurs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kurs")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("NomKurs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("NonPPn")
                        .HasColumnType("bit");

                    b.HasKey("FcGlTransDId");

                    b.HasIndex("FcGlTransHId");

                    b.ToTable("FcGlTransDs");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcGlTransH", b =>
                {
                    b.Property<int>("FcGlTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcGlTransHId"), 1L, 1);

                    b.Property<string>("Cek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Debet")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeGl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonPPn")
                        .HasColumnType("bit");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("FcGlTransHId");

                    b.ToTable("FcGlTransHs");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcPrintGl", b =>
                {
                    b.Property<int>("FcPrintGlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcPrintGlId"), 1L, 1);

                    b.Property<bool>("CetakBln1")
                        .HasColumnType("bit");

                    b.Property<bool>("CetakBln2")
                        .HasColumnType("bit");

                    b.Property<bool>("CetakDetil")
                        .HasColumnType("bit");

                    b.Property<bool>("CetakGaris1")
                        .HasColumnType("bit");

                    b.Property<bool>("CetakGaris2")
                        .HasColumnType("bit");

                    b.Property<bool>("CetakHide")
                        .HasColumnType("bit");

                    b.Property<bool>("CetakNegatif")
                        .HasColumnType("bit");

                    b.Property<bool>("CetakTebal")
                        .HasColumnType("bit");

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumRekap1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("JumRekap2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("JumSaldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("JumTran1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("JumTran2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeCetak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoBaris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoRek1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoRek2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Persen1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Persen2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Qty1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Qty2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RumusBaris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spasi")
                        .HasColumnType("int");

                    b.HasKey("FcPrintGlId");

                    b.ToTable("FcPrintGls");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcPrintTP", b =>
                {
                    b.Property<int>("FcPrintTPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcPrintTPId"), 1L, 1);

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JnsReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeCetak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaCetak")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FcPrintTPId");

                    b.ToTable("FcPrintTPs");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcTransD", b =>
                {
                    b.Property<int>("FcTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcTransDId"), 1L, 1);

                    b.Property<decimal>("Debet")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FcTransHId")
                        .HasColumnType("int");

                    b.Property<string>("GlAcct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlDept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumKurs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kurs")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("NomKurs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("NonPPn")
                        .HasColumnType("bit");

                    b.HasKey("FcTransDId");

                    b.HasIndex("FcTransHId");

                    b.ToTable("FcTransDs");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcTransH", b =>
                {
                    b.Property<int>("FcTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcTransHId"), 1L, 1);

                    b.Property<string>("Cek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Debet")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FcComKode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeGl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kredit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonPPn")
                        .HasColumnType("bit");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("FcTransHId");

                    b.ToTable("FcTransHs");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcGlTransD", b =>
                {
                    b.HasOne("eSoft.Financial.Model.FcGlTransH", "FcGlTransH")
                        .WithMany("FcGlTransDs")
                        .HasForeignKey("FcGlTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FcGlTransH");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcTransD", b =>
                {
                    b.HasOne("eSoft.Financial.Model.FcTransH", "FcTransH")
                        .WithMany("FcTransDs")
                        .HasForeignKey("FcTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FcTransH");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcGlTransH", b =>
                {
                    b.Navigation("FcGlTransDs");
                });

            modelBuilder.Entity("eSoft.Financial.Model.FcTransH", b =>
                {
                    b.Navigation("FcTransDs");
                });
#pragma warning restore 612, 618
        }
    }
}
