<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Accounting-C0DD8C5E-2FE3-4D23-B9F9-20334E339888</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\PDFKontrak\**" />
    <Content Remove="wwwroot\PDFKontrak\**" />
    <EmbeddedResource Remove="wwwroot\PDFKontrak\**" />
    <None Remove="wwwroot\PDFKontrak\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Components\ModalTestRunComponent.razor" />
    <Content Remove="Pages\ModuleBank\TransBank\EditAddTransBank.razor" />
  </ItemGroup>



  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Abstractions" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eSoft.Asset\eSoft.Asset.csproj" />
    <ProjectReference Include="..\eSoft.CashBank\eSoft.CashBank.csproj" />
    <ProjectReference Include="..\eSoft.Company\eSoft.Company.csproj" />
    <ProjectReference Include="..\eSoft.Financial\eSoft.Financial.csproj" />
    <ProjectReference Include="..\eSoft.Fungsi\eSoft.Fungsi.csproj" />
    <ProjectReference Include="..\eSoft.Hutang\eSoft.Hutang.csproj" />
    <ProjectReference Include="..\eSoft.LaporanStock\eSoft.LaporanStock.csproj" />
    <ProjectReference Include="..\eSoft.Ledger\eSoft.Ledger.csproj" />
    <ProjectReference Include="..\eSoft.Order\eSoft.Order.csproj" />
    <ProjectReference Include="..\eSoft.Pembelian\eSoft.Pembelian.csproj" />
	  <ProjectReference Include="..\eSoft.Penjualan\eSoft.Penjualan.csproj" />
    <ProjectReference Include="..\eSoft.Persediaan\eSoft.Persediaan.csproj" />
    <ProjectReference Include="..\eSoft.Piutang\eSoft.Piutang.csproj" />
    <ProjectReference Include="..\eSoft.TestRun\eSoft.TestRun.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Pages\ModuleAsset\Asset\SetupAsset.razor" />
    <None Include="Pages\ModuleJual\OrderJual\AddTransSalesOrder.razor" />
    <None Include="Pages\ModuleJual\OrderJual\EditTransOrderJual.razor" />
    <None Include="Pages\ModuleJual\OrderJual\TransOrderJual.razor" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Pages\ModuleJual\Laporan\LaporanJualPerCustomer.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
