<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <!--<ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eSoft.Asset\eSoft.Asset.csproj" />
    <ProjectReference Include="..\eSoft.CashBank\eSoft.CashBank.csproj" />
    <ProjectReference Include="..\eSoft.Hutang\eSoft.Hutang.csproj" />
    <ProjectReference Include="..\eSoft.Ledger\eSoft.Ledger.csproj" />
    <ProjectReference Include="..\eSoft.Pembelian\eSoft.Pembelian.csproj" />
    <ProjectReference Include="..\eSoft.Penjualan\eSoft.Penjualan.csproj" />
    <ProjectReference Include="..\eSoft.Persediaan\eSoft.Persediaan.csproj" />
    <ProjectReference Include="..\eSoft.Piutang\eSoft.Piutang.csproj" />
  </ItemGroup>

</Project>
