<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eSoft.Order\eSoft.Order.csproj" />
    <ProjectReference Include="..\eSoft.Pembelian\eSoft.Pembelian.csproj" />
    <ProjectReference Include="..\eSoft.Penjualan\eSoft.Penjualan.csproj" />
  </ItemGroup>

</Project>
