// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSoft.TestRun.Data;

#nullable disable

namespace Accounting.Migrations.DbContextTestRunMigrations
{
    [DbContext(typeof(DbContextTestRun))]
    [Migration("20250407060410_InitialTestRun")]
    partial class InitialTestRun
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eSoft.TestRun.Model.TsSchedule", b =>
                {
                    b.Property<int>("TsScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TsScheduleId"), 1L, 1);

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daerah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daftar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dokumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasilTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PInvoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tested")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TglKirim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglTest")
                        .HasColumnType("datetime2");

                    b.Property<string>("TsOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TsScheduleId");

                    b.ToTable("TsSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
